### ISSUE TITLE
Unwinnable Scenario - No Warp Items After Meeting Lexis

### ISSUE THREAD

**Issue by jrconway3** [abyssonym/terrorwave#2]
I'm creating this issue anyway even though I know it most likely won't be addressed. The last time this randomizer was updated was back in 2017.

So, here's the situation:

1. I used "1" Randomization Setting on All Options Except Enemies and "Others"
2. No character could learn Warp or Escape all the way to Dekar
3. Dekar could learn Escape, but I didn't bother returning to older towns to try learning Warp
4. Even if he could learn Warp, Dekar is lost at Karlloon Shrine
5. I reached Lexis who tells me to go back to Aleyn to Speak with Jyad
6. I walk back to Narcysus because I don't have Warp
7. Jyad is NOT at the port in Narcysus
8. No Shops on Estoc Continent Sell Warp Items
9. I completed Flower Mountain (no boss) and no Warp Items Either

I think the best solution to this problem is something like:
1. Allow Jyad to still show up in Narcysus
2. Force Warp Items to be Sold at At Least ONE Shop on Estoc Continent

#2 is probably the best bet for this issue.

I know this issue probably won't get resolved, but I figured it was best to report it anyway. If someone else tries to run the Randomizer, at least they should be aware to make sure they buy at least one Warp item before heading to Aleyn. Granted, I don't recall seeing any Warp items at all, but I also wasn't paying close attention.

If its possible for no Warp Items to exist and no characters to learn Warp, it makes the game Unwinnable once you have to Warp back to Jyad. I didn't even think it'd be possible to have a situation where you'd ever get softlocked like this, but I forgot Jyad disappeared by the time you meet Lexis.

**Comment by abyssonym** [comment]
This should be resolved in version 3
