### ISSUE TITLE
Crash in open world randomizer

### ISSUE THREAD

**Issue by sorlok** [abyssonym/terrorwave#3]
With flag STW and seed Lufia2.stw.1680453843.sfc, I go to the "Capsule Monster Shrine" (the tree on the world map) and pick up a crown. Pressing "A" once appears to do nothing; pressing "A" again crashes back to the title screen.
![ld_crash](https://user-images.githubusercontent.com/513512/229367216-4dc3c9d5-44b4-432d-b14b-b870041249a3.png)

**Comment by sorlok** [comment]
Similarly, there is a crown in "Cave to Sundletan"; if I press "A" twice on it, then the staircase back up no longer works.
![ld_freeze](https://user-images.githubusercontent.com/513512/229367410-26dd87b8-f30e-4ca7-82a1-6ea18d0c55ff.png)

**Comment by abyssonym** [comment]
Oh, you're not supposed to interact with crowns. I'll fix this soon, just ignore them until I do.

**Comment by sorlok** [comment]
Ah, that makes sense, thanks!
